### ISSUE TITLE
Support for ng-model-options timezone

### ISSUE THREAD

**Issue by hexadecy** [beenote/angular-material-datetimepicker#27]
Issue: Date is always displayed in local time
Expected: `ng-model` should respect the `ng-model-options`

Code:
`<input mdc-datetime-picker date="true" time="false" type="text" format="MM/DD/YYYY Z" show-todays-date ng-model="date" ng-model-options="{ timezone: 'utc' }" />`

**Comment by ptitdam2001** [comment]
Hi there is a bug onto the version 1.12.0 with angular 1.5.9.

A the end of the process, we have that error

`
TypeError: Cannot read property 'timezone' of undefined
    at eval (angular-material-datetimepicker.js:259)
    at processQueue (angular.js:16606)
    at eval (angular.js:16622)
    at Scope.$eval (angular.js:17913)
    at Scope.$digest (angular.js:17727)
    at eval (angular.js:17952)
    at completeOutstandingRequest (angular.js:6035)
    at eval (angular.js:6314)
`
The line 259 is `if (ngModel.$options.$$options.timezone) {`, I think you should define ngModel.$options.$$options if not defined.

If I add the attribute ng-model-options, I have the error below: 

`
angular.js:14110 TypeError: ngModel.$options.createChild is not a function
    at Object.link (webpack:///./node_modules/ng-material-datetimepicker/js/angular-material-datetimepicker.js?:208:70)
    at eval (webpack:///./node_modules/angular/angular.js?:1259:18)
    at eval (webpack:///./node_modules/angular/angular.js?:10089:44)
    at invokeLinkFn (webpack:///./node_modules/angular/angular.js?:10095:9)
    at nodeLinkFn (webpack:///./node_modules/angular/angular.js?:9492:11)
    at compositeLinkFn (webpack:///./node_modules/angular/angular.js?:8757:13)
    at nodeLinkFn (webpack:///./node_modules/angular/angular.js?:9486:11)
    at compositeLinkFn (webpack:///./node_modules/angular/angular.js?:8757:13)
    at nodeLinkFn (webpack:///./node_modules/angular/angular.js?:9486:11)
    at compositeLinkFn (webpack:///./node_modules/angular/angular.js?:8757:13) <input mdc-datetime-picker="" id="datetime-picker" date="true" time="true" type="text" format="DD-MM-YYYY HH:mm" min-date="$ctrl.minDate" ng-model="$ctrl.ngModel" ng-model-options="{ timezone: 'utc' }" readonly="readonly" ng-required="!$ctrl.ngRequired" ng-disabled="$ctrl.ngDisabled" ng-change="$ctrl.ngChange()" cancel-text="{{ 'datepicker.cancel' | translate }}" today-text="{{ 'datepicker.today' | translate }}" ok-text="{{ 'datepicker.ok' | translate }}" week-start="1" placeholder="{{$ctrl.placeholder}}" class="ng-pristine ng-untouched ng-valid ng-isolate-scope">
`

May be it comes from me but the component is working with the version 1.11.0

**Comment by hexadecy** [comment]
Yep, it's an issue with 1.12.0 and angular < 1.6

**Comment by hexadecy** [comment]
Fixed by https://github.com/beenote/angular-material-datetimepicker/commit/b35700352bc3566531b332a6c877be703cf7754c

**Comment by hexadecy** [comment]
https://github.com/beenote/angular-material-datetimepicker/releases/tag/v1.13.0
